
subsystem = {"UV filter":              "liquid tanks and plumbing",
	     "CO2 solenoid":           "internal atmosphere",
	     "N2 solenoid":            "internal atmosphere",
	     "heater":                 "liquid tanks and plumbing",
	     "chiller":                "liquid tanks and plumbing",
	     "fan 1":                  "internal atmosphere",
	     "fan 2":                  "internal atmosphere",
	     "O2 concentrator":        "internal atmosphere",
	     "LED":		       "internal atmosphere",
	     "main pump": 	       "growth medium",
	     "condensate pump":        "liquid tanks and plumbing",
	     "nutrient 1 dosing":      "liquid tanks and plumbing",
	     "nutrient 2 dosing":      "liquid tanks and plumbing",
	     "pH dosing": 	       "liquid tanks and plumbing",
	     "nutrient 1 circulation": "liquid tanks and plumbing",
	     "air bubbler":	       "liquid tanks and plumbing",
	     "filter pump":	       "liquid tanks and plumbing",
	     "nutrient 2 circulation": "liquid tanks and plumbing",
	     "humidifier pump":	       "internal atmosphere",
	     "main tank circulation":  "liquid tanks and plumbing",
	     "dehumidifier":	       "internal atmosphere"}
