#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST
	
# set up firebase
firebase = REST()
	
# import sensors by category
from UART import flow_meter

# declare sensor
sensor = flow_meter(4)

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with open('/tmp/S111', 'w') as sense: sense.write(str(reading)+'\n')

	# take time stamp
	time_stamp = int(time.time())

	# set up database
	entry = {time_stamp: reading}

	# PATCH entry
	result = firebase.PATCH(entry, "data/sensors/liquid_tanks_and_plumbing/S111.json")
