#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST
	
# set up firebase
firebase = REST()
	
# import sensors by category
from I2C import electrical_conductivity

# declare sensor
sensor = electrical_conductivity(0x66)

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with open('/tmp/S101', 'w') as sense: sense.write(str(reading)+'\n')

	# take time stamp
	time_stamp = int(time.time())

	# set up database
	entry = {time_stamp: reading}

	# PATCH entry
	result = firebase.PATCH(entry, "/data/sensors/liquid_tanks_and_plumbing/S101.json")
