#!/usr/bin/env python

# need this to post to database
import firebase
	
# import sensors by category
from I2C import pH

# declare sensor
sensor = pH(0x65)

# take reading
reading = sensor.read()

# write to temporary file for API
with sense as open('/tmp/S102'): sense.write(reading)

# post to databases
result = firebase.post('/data', reading)
