#!/usr/bin/env python

# need this to post to database
import firebase
	
# import sensors by category
from I2C import dissolved_oxygen

# declare sensor
sensor = dissolved_oxygen(0x61)

# take reading
reading = sensor.read()

# write to temporary file for API
with sense as open('/tmp/S104'): sense.write(reading)

# post to databases
result = firebase.post('/data', reading)
