#!/usr/bin/env python

# need this for epoch
import time

# need this for clean command
import os

# need this to post to database
from REST import REST
	
# set up firebase
firebase = REST()
	
# import sensors by category
from one_wire import temperature

# declare sensor
sensor = temperature('28-00000673a8a7')

# start counter
count = int()

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# junk reading
	if reading < 0: continue

	# write to temporary file for API
	with open('/tmp/S103', 'w') as sense: sense.write(str(reading)+'\n')

	# take time stamp
	time_stamp = int(time.time())

	# set up database
	entry = {time_stamp: reading}

	# PATCH entry
	result = firebase.PATCH(entry, "data/sensors/liquid_tanks_and_plumbing/S103.json")

	if count % 10000 == 0: os.system("clean 10")

	# increment count
	count += 1
