#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST
	
# set up firebase
firebase = REST()
	
# import sensors by category
from one_wire import temperature

# declare sensor
sensor = temperature('28-0000065f27cc')

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# throw out junk readings
	if reading < 0: continue

	# write to temporary file for API
	with open('/tmp/S201', 'w') as sense: sense.write(str(reading)+'\n')

	# take time stamp
	time_stamp = int(time.time())

	# set up database
	entry = {time_stamp: reading}

	# PATCH entry
	result = firebase.PATCH(entry, "data/sensors/growth_medium/S201.json")
