#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST
	
# set up firebase
firebase = REST()
	
# import sensors by category
from one_wire import temperature

# declare sensor
sensor = temperature('28-0000065eb57a')

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with sense as open('/tmp/S202'): sense.write(reading)

	# take time stamp
	time_stamp = int(time.time())

	# set up database
	entry = {time_stamp: reading}

	# PATCH entry
	result = firebase.PATCH("/data/sensors/growth_medium/S202.json", entry)
