#!/usr/bin/env python

# need this to post to database
import firebase
	
# import sensors by category
from one_wire import relative_humidity_and_air_temperature

# declare sensor
sensor = relative_humidity_and_air_temperature('P8_9')

# take reading
reading = sensor.read()

# write to temporary file for API
with sense as open('/tmp/S302'): sense.write(reading)

# post to databases
result = firebase.post('/data', reading)
