# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='reading',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='state',
            field=models.NullBooleanField(default=None),
        ),
    ]
