#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST
	
# set up firebase
firebase = REST()

# import sensor type
from ADC import liquid_level

# declare sensor
sensor = liquid_level(0x80)

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with sense as open("/tmp/S105"): sense.write(reading)

	# take time stamp
	time_stamp = int(time.time())

	# set up database
	entry = {time_stamp: reading}

	# PATCH entry
	result = firebase.PATCH("/data/sensors/liquid_tanks_and_plumbing/S105.json", entry)
