#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST

# set up firebase
firebase = REST()
	
# import sensor type
from ADC import moisture

# declare sensor
sensor = moisture(0xC0)

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with open('/tmp/S210', 'w') as sense: sense.write(str(reading)+'\n')

	# take time stamp
	epoch = int(time.time())

	# set up database entry
	entry = {epoch: reading}

	# PATCH entry
	result = firebase.PATCH(entry, "data/sensors/growth_medium/S210.json")
