#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST

# set up firebase
firebase = REST()
	
# import sensor type
from ADC import oxygen

# declare sensor
sensor = oxygen()

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with sense as open('/tmp/S304'): sense.write(reading)

	# take time stamp
	epoch = int(time.time())

	# set up database entry
	entry = {epoch: reading}

	# PATCH entry
	result = firebase.PATCH("/data/sensors/internal_atmosphere/S304.json", entry)
