#!/usr/bin/env python

# need this for epoch
import time

# need this to post to database
from REST import REST

# set up firebase
firebase = REST()
	
# import sensor type
from ADC import oxygen

# declare sensor
sensor = oxygen()

# do this indefinitely
while True:
   
	# take reading
	reading = sensor.read()

	# write to temporary file for API
	with open('/tmp/S304', 'w') as sense: sense.write(str(reading))

	# take time stamp
	epoch = int(time.time())

	# set up database entry
	entry = {epoch: reading}

	# PATCH entry
	result = firebase.PATCH(entry, "/data/sensors/internal_atmosphere/S304.json")
