#!/usr/bin/env python

# need this to post to database
import firebase
	
# import sensor type
from ADC import oxygen

# declare sensor
sensor = oxygen()
   
# take reading
reading = sensor.read()

# write to temporary file for API
with sense as open('/tmp/S304'): sense.write(reading)

# post to databases
result = firebase.post('/data', reading)
