#!/usr/bin/env python

# need this to wait
import time

# need this for CO2 solenoid valve
from API.actuators import V

# need this for CO2 sensor
from API.sensors import S

# do this indefinitely
while True:

	# take CO2 reading
	reading = S[305].read()

	# if reading is under 1250 ppm, toggle a duty cycle
	if reading < .125:

		# duty cycle
		V[3].toggle()
		time.sleep(.1)
		V[3].toggle()

		# wait 30 seconds
		time.sleep(30)
