#!/usr/bin/env python

# need this to wait
import time

# need this for REST API
from API.REST import REST

# need this for conversions
from API.conversions import senseIDtoSysID

# need this for sorted dictionary
import collections

# set up REST backend 
firebase = REST("https://cumarsoasis.firebaseio.com/")

# initialize sensors as not awake
awake = {'EC1': bool(), 'pH1': bool(), 'temp1': bool(), 'temp2': bool(), 'temp3': bool(), 'temp4': bool(), 'CO2': bool(), 'TP1': bool(), 'TP2': bool(). 'O2': bool()}

# do this indefinitely
while True:

	# wait thirty seconds
	time.sleep(30)

	# for each temperature sensor
	for senseID in awake:

		# set SysID
		SysID = senseIDtoSysID[senseID]

		# set historical table
		table = "sensors/historical/S" + str(SysID) + ".json"

		# get data
		data = firebase.GET(table)

		# convert keys to integers
		data = {int(k): v for k, v in data.items() if v >= 0}

		# sort data by key
		data = collections.OrderedDict(sorted(data.items()))

		# split into epochs and readings
		epochs   = data.keys()
		readings = data.values()

		# record latest time
		latest_time = int(time.time())

		# set cutoff points
		minute_cutoff = latest_time - 60
		hour_cutoff   = latest_time - 3600

		# initialize data windows
		minute = dict()
		hour   = dict()

		# for each time
		for epoch in epochs:

			# filter out entries
			if epoch > minute_cutoff: minute[epoch] = data[epoch]
			if epoch > hour_cutoff:   hour[epoch]   = data[epoch]

		# set tables
		minute_table = "sensors/minute/S" + str(SysID) + ".json"
		hour_table   = "sensors/hour/S"   + str(SysID) + ".json"

		# post data
		firebase.PUT(minute, minute_table)
		firebase.PUT(hour,   hour_table)
