#!/usr/bin/env python

# need this to wait
import time

# need this for CO2 solenoid valve
from API.actuators import V

# do this indefinitely
#while True:

# duty cycle
V[3].toggle()
time.sleep(.5)
V[3].toggle()

# wait thirty minutes
#	time.sleep(1800)
