#!/bin/bash
# 
# this runs the sensedaemon and detaches from any specific terminal
#
# make sure to while you have sudo privileges (a hacky way is just to type "sudo ls" before running this) 
# otherwise, you will be prompted for a password, and it will just write that prompt to the sensor data over and over again

PWD=`pwd`

sudo nohup $PWD/sensedaemon > /dev/null 2>$PWD/readings/errorlog.txt &
