#!/bin/bash

# initialize error logs
mkdir -p /tmp/errorlogs

# start actuators
initiate

# wake up
nohup /home/atecce/MarsOASIS/BBB/focus > /tmp/errorlogs/general 2>&1 &

# keep it clean
nohup /home/atecce/MarsOASIS/BBB/clean > /tmp/errorlogs/general 2>&1 &
