#!/bin/bash

# written by Ryan Bohannon

# Simple script to flip the gpio devices on/off

if [ $# != 1 ]; then
  printf "Warning! Please be extremely careful running this script!\n"
  printf "Usage: flipbit {GPIO #}\n"
  printf "       flipbit 51\n"
  exit 1;
fi

device="/sys/devices/virtual/gpio/gpio$1/value"

if [ -f $device ]; then
  value=$(cat $device)

  if [ $value == 0 ]; then
    echo 1 > $device
  else 
    echo 0 > $device
  fi

else
  printf "error"
fi

