#!/usr/bin/env python

# need this to monitor processes
import psutil

# do this indefinitely
while True:

	# initialize sensors as not awake
	awake = {'EC1': bool(), 'pH1': bool(), 'temp1': bool(), 'temp2': bool(), 'temp3': bool(), 'temp4': bool(), 'CO2': bool(), 'TP1': bool(), 'TP2': bool()}

	# for each pid
	for pid in psutil.pids(): 

		try: 

			# for each sensor
			for sensor in awake:
			
				# check if it's awake
				if sensor in psutil.Process(pid).name(): sensor[awake] = True

		# catch Zombies
		except psutil.ZombieProcess: continue

	# for each sensor
	for sensor in awake: 

		# if the sensor isn't awake, wake it
		if not awake[sensor]: os.system("wake " + sensor)
