#!/bin/bash

divider===============================
divider=$divider$divider

header="\n %-10s %11s\n"
format=" %-10s %8d\n"

width=23

printf "$header" "GPIO" "Value"
printf "%$width.${width}s\n" "$divider"
 


for i in `ls -v /sys/devices/virtual/gpio*`;

  do 
    
    if [ -f "/sys/devices/virtual/gpio/$i/value" ]; then
     
      value=$(cat /sys/devices/virtual/gpio/$i/value)
      printf "$format" \
      $i $value \

    ;fi

  done;
