#!/bin/bash

# if number of arguments isn't one or two
if [ $# != 1 ]; then

	# display usage
	printf "\n"
	printf "Usage: read_sensor <sensor name>\n"
	printf "\n"

	# exit with error status 1
	exit 1
fi

# sensor is first argument
sensor="$1" 


# wrap bash around python
sudo python /home/atecce/OASIS/BBB/read_sensor.py $sensor
