#!/usr/bin/env python

# need this for command line arguments and for the path
import sys

# need this to use cat
import os

# returns the SysID when given senseID
senseIDtoSysID = {"EC1":	  101,
	   	  "EC2":	  205,

	   	  "temp1":        103,
	   	  "temp2":	  201,
	   	  "temp3":	  202,
	   	  "temp4":	  203,

	   	  "DO":   	  104,

	   	  "LL1": 	  105,
	   	  "LL2": 	  106,
	   	  "LL3": 	  107,
	   	  "LL4": 	  108,
	   	  "LL5": 	  109,
	   	  "LL6": 	  112,

	   	  "flow_meter1":  110,
	   	  "flow_meter2":  111,

	   	  "pH1":	  102,
	   	  "pH2":	  206,

	   	  "MO1":	  208,
	   	  "MO2":	  209,
	   	  "MO3":	  210,
	   	  "MO4":	  211,

	   	  "RHT1":	  301,
	   	  "RHT2":	  302,
	   	  "RHT3":	  401,

	   	  "TP1":	  303,
	   	  "TP2":	  402,

	   	  "O2":	  	  304,

	   	  "CO2":	  305,

	   	  "PAR1":	  306,
	   	  "PAR2": 	  403}

def main(argv):

	# read in senseID
	senseID = argv[1]

	# check if senseID is valid
	if senseID in senseIDtoSysID:

		# set SysID
		SysID = senseIDtoSysID[senseID]

		# display comments of file
		os.system("cat /tmp/S" + str(SysID))

	# catch error (probably needs work)
	else: print "Invalid sensor name"

if __name__ == "__main__": main(sys.argv)
