#!/usr/bin/env python

# need this for command line arguments and for the path
import sys

# need this to use nohup
import os

# need this to look up data communication types
from API.conversions import data_comm_lookup

def main(argv):

	# read in senseID
	SysID = int(argv[1])

	# check if senseID is valid
	if SysID in data_comm_lookup:

		# set data communication type
		data_comm_type = data_comm_lookup[SysID]

		# display comments of file
		os.system("sudo nohup sensedaemons/" + data_comm_type + "/S" + str(SysID) + " > /dev/null 2>sensedaemons/" + data_comm_type + "/errorlogs/S" + str(SysID) + ".txt &")

	# catch error (probably needs work)
	else: print "Invalid sensor name"

if __name__ == "__main__": main(sys.argv)
